!theme nord from https://raw.githubusercontent.com/ansanloms/nord-plantuml-theme/v0.1.0/themes

skinparam {
	preserveAspectRatio xMidYMid meet
	handwritten true

	BackgroundColor transparent

	Padding 8
	ParticipantPadding 12
	BoxPadding 8

	DefaultFontName "Zen Kurenaido"
	DefaultFontSize 18
	DefaultFontStyle bold
}

'vim:set noexpandtab:
